[package]
name = "rust-lambda"
version = "0.1.0"
edition = "2021"
authors = ["Dawson Freitas Israel <dawsonfi@gmail.com"]

[dependencies]
lambda_runtime = "0.4.1"
tokio = "1.14.0"
serde = "1.0.130"
serde_json = "1.0.59"