[package]
name = "rust-lambda"
version = "0.1.0"
edition = "2021"
authors = ["Dawson Freitas Israel <dawsonfi@gmail.com"]

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
lambda_runtime = "0.5.0"
lambda_http = "0.5.0"
log = "0.4"
env_logger = "0.9.0"