[package]
name = "rust-lambda"
version = "0.1.0"
edition = "2021"
authors = ["Dawson Freitas Israel <dawsonfi@gmail.com"]

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
lambda_runtime = "0.5.0"